const vscode = require('vscode')
const fs = require('fs')

let makeFolder = vscode.commands.registerCommand(
  'letytools.generateFolder',
  async function () {
    // 입력 박스를 열어서
    let result = vscode.window.showInputBox({
      title: 'Type the name of new directory',
      prompt: ''
    })

    // 입력을 받는다.
    let value = await result.then(
      function (value) {
        return value
      },
      function (reason) {
        vscode.window.showErrorMessage(`folder generation canceled : ${reason}`)
        return '????'
      }
    )

    if (value === '????') {
      return
    }

    if (value === '' || value === undefined) {
      vscode.window.showErrorMessage(`folder generation canceled : empty input`)
      return
    }

    console.log(value)

    // 열린 워크스페이스가 없으면 그냥 닫는다.
    let workspaceName = vscode.workspace.name
    if (workspaceName === undefined) {
      vscode.window.showInformationMessage('need workspace!')
      return
    }

    // 워크 스페이스 목록에서 선택한다.
    let wsfolders = vscode.workspace.workspaceFolders

    var pickedWs
    var pickedWsIndex

    if (wsfolders.length == 1) {
      // 만약 열린 워크스페이스가 하나라면 그걸 고른다.
      pickedWs = wsfolders[0]
      pickedWsIndex = 0
    } else {
      pickedWs = await vscode.window.showQuickPick(
        wsfolders.map((value, _index, __array) => {
          pickedWsIndex = value.index
          return value.name
        })
      )
    }

    console.log(pickedWs)
    console.log(pickedWsIndex)

    // 해당 폴더가 플러터 프로젝트이면.

    let ws = wsfolders[pickedWsIndex]

    let path = ws.uri.fsPath
    console.log(path)

    let folderPath = `${path}/lib/${value}`
    // 폴더를 만들고
    fs.mkdirSync(folderPath, 0o766)
    fs.writeFileSync(
      `${folderPath}/${value}.dart`,
      '// This file is generated by letytools'
    )
  }
)

export default makeFolder
